/* The following code was generated by JFlex 1.6.1 */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Analizador2.l</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\4\1\61\1\61\1\4\22\0\1\6\1\33\1\13"+
    "\2\0\1\40\1\32\1\14\1\26\1\27\1\36\1\30\1\54\1\10"+
    "\1\11\1\37\12\1\1\53\1\52\1\34\1\25\1\35\2\0\4\2"+
    "\1\7\25\2\1\57\1\12\1\60\1\0\1\3\1\0\1\22\1\46"+
    "\1\43\1\45\1\20\1\21\1\2\1\44\1\41\1\2\1\50\1\23"+
    "\1\2\1\5\1\42\2\2\1\16\1\24\1\15\1\17\1\51\1\47"+
    "\3\2\1\55\1\31\1\56\7\0\1\61\u1fa2\0\1\61\1\61\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\5\3\1\5\3"+
    "\1\6\1\7\1\10\1\11\1\1\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\6\3\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\0\1\30\4\0\7\3"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\3"+
    "\1\40\3\3\1\41\3\3\1\2\1\30\1\0\2\42"+
    "\7\3\1\43\7\3\1\0\1\44\1\3\1\45\1\46"+
    "\3\3\1\47\1\50\4\3\1\51\1\30\1\3\1\52"+
    "\1\53\3\3\1\54\1\55\1\56\1\57\1\3\1\60"+
    "\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\62\0\u012c"+
    "\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc"+
    "\0\62\0\62\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8"+
    "\0\62\0\62\0\62\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2"+
    "\0\u0514\0\62\0\62\0\62\0\62\0\62\0\62\0\62"+
    "\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\62\0\62"+
    "\0\62\0\62\0\62\0\62\0\62\0\u0802\0\226\0\u0834"+
    "\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992\0\u09c4"+
    "\0\u09f6\0\u05dc\0\62\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0"+
    "\0\u0b22\0\u0b54\0\226\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e"+
    "\0\u0c80\0\u0cb2\0\u0ce4\0\226\0\u0d16\0\226\0\226\0\u0d48"+
    "\0\u0d7a\0\u0dac\0\226\0\226\0\u0dde\0\u0e10\0\u0e42\0\u0e74"+
    "\0\226\0\u09f6\0\u0ea6\0\226\0\226\0\u0ed8\0\u0f0a\0\u0f3c"+
    "\0\226\0\226\0\226\0\226\0\u0f6e\0\226\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\5\1\4\1\7"+
    "\1\10\1\2\1\11\1\12\1\13\1\14\1\4\1\15"+
    "\1\16\2\4\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\4\1\35\1\4\1\36\1\37\1\40\1\4\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\64\0"+
    "\1\3\1\0\1\51\3\0\1\52\1\0\1\53\6\0"+
    "\1\52\42\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\10\4\14\0\11\4\14\0\3\5\54\0\3\4\1\5"+
    "\1\6\1\5\1\4\5\0\10\4\14\0\11\4\11\0"+
    "\1\53\61\0\2\54\2\0\4\54\1\0\2\54\1\0"+
    "\14\54\1\55\20\54\11\0\2\56\1\0\5\56\1\0"+
    "\2\56\1\0\14\56\1\57\20\56\11\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\1\4\1\60\6\4\14\0"+
    "\11\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\3\4\1\61\4\4\14\0\11\4\11\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\6\4\1\62\1\4\14\0"+
    "\11\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\2\4\1\63\2\4\1\64\1\65\1\4\14\0\11\4"+
    "\11\0\3\4\1\0\1\4\1\0\1\4\5\0\10\4"+
    "\14\0\6\4\1\66\2\4\35\0\1\67\64\0\1\70"+
    "\62\0\1\71\62\0\1\72\54\0\1\73\61\0\1\74"+
    "\61\0\1\75\35\0\3\4\1\0\1\76\1\0\1\4"+
    "\5\0\4\4\1\77\3\4\14\0\11\4\11\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\5\4\1\100\2\4"+
    "\14\0\3\4\1\101\5\4\11\0\3\4\1\0\1\4"+
    "\1\0\1\4\5\0\3\4\1\102\4\4\14\0\1\4"+
    "\1\103\7\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\1\4\1\104\6\4\14\0\11\4\11\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\10\4\14\0\3\4"+
    "\1\105\5\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\10\4\14\0\1\4\1\106\7\4\11\0\1\107"+
    "\61\0\1\110\6\0\1\111\17\0\1\111\32\0\1\53"+
    "\5\0\1\52\10\0\1\52\42\0\2\54\2\0\4\54"+
    "\1\0\1\54\1\112\1\0\14\54\1\55\20\54\41\0"+
    "\1\54\31\0\2\56\1\0\5\56\1\0\2\56\1\113"+
    "\14\56\1\57\20\56\41\0\1\56\31\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\2\4\1\114\5\4\14\0"+
    "\11\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\1\115\7\4\14\0\11\4\11\0\3\4\1\0\1\4"+
    "\1\0\1\4\5\0\7\4\1\116\14\0\11\4\11\0"+
    "\3\4\1\0\1\117\1\0\1\4\5\0\10\4\14\0"+
    "\11\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\6\4\1\120\1\4\14\0\11\4\11\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\10\4\14\0\1\4\1\121"+
    "\7\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\10\4\14\0\1\122\10\4\11\0\3\4\1\0\1\4"+
    "\1\0\1\4\5\0\1\123\7\4\14\0\11\4\11\0"+
    "\3\4\1\0\1\4\1\0\1\4\5\0\7\4\1\124"+
    "\14\0\11\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\5\4\1\125\2\4\14\0\11\4\11\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\4\4\1\126\3\4"+
    "\14\0\11\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\2\4\1\127\5\4\14\0\11\4\11\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\3\4\1\130\4\4"+
    "\14\0\11\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\10\4\14\0\1\131\10\4\11\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\10\4\14\0\1\132\10\4"+
    "\11\0\1\3\5\0\1\52\1\0\1\53\6\0\1\52"+
    "\42\0\1\110\1\0\1\133\57\0\1\110\61\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\3\4\1\134\4\4"+
    "\14\0\11\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\2\4\1\135\5\4\14\0\11\4\11\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\3\4\1\136\4\4"+
    "\14\0\11\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\10\4\14\0\2\4\1\137\6\4\11\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\7\4\1\140\14\0"+
    "\11\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\5\4\1\141\2\4\14\0\11\4\11\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\1\142\7\4\14\0\11\4"+
    "\11\0\3\4\1\0\1\4\1\0\1\4\5\0\3\4"+
    "\1\143\4\4\14\0\11\4\11\0\3\4\1\0\1\4"+
    "\1\0\1\4\5\0\1\4\1\144\6\4\14\0\11\4"+
    "\11\0\3\4\1\0\1\4\1\0\1\4\5\0\5\4"+
    "\1\145\2\4\14\0\11\4\11\0\3\4\1\0\1\4"+
    "\1\0\1\4\5\0\10\4\14\0\5\4\1\146\3\4"+
    "\11\0\3\4\1\0\1\4\1\0\1\4\5\0\5\4"+
    "\1\147\2\4\14\0\11\4\11\0\3\4\1\0\1\4"+
    "\1\0\1\4\5\0\6\4\1\150\1\4\14\0\11\4"+
    "\11\0\3\4\1\0\1\4\1\0\1\4\5\0\10\4"+
    "\14\0\4\4\1\151\4\4\11\0\1\152\61\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\1\4\1\153\6\4"+
    "\14\0\11\4\11\0\3\4\1\0\1\4\1\0\1\4"+
    "\5\0\3\4\1\154\4\4\14\0\11\4\11\0\3\4"+
    "\1\0\1\4\1\0\1\4\5\0\1\155\7\4\14\0"+
    "\11\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\10\4\14\0\2\4\1\156\6\4\11\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\2\4\1\157\5\4\14\0"+
    "\11\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\6\4\1\160\1\4\14\0\11\4\11\0\3\4\1\0"+
    "\1\4\1\0\1\4\5\0\10\4\14\0\7\4\1\161"+
    "\1\4\11\0\3\4\1\0\1\4\1\0\1\4\5\0"+
    "\3\4\1\162\4\4\14\0\11\4\11\0\3\4\1\0"+
    "\1\163\1\0\1\4\5\0\10\4\14\0\11\4\11\0"+
    "\3\4\1\0\1\4\1\0\1\4\5\0\10\4\14\0"+
    "\3\4\1\164\5\4\11\0\3\4\1\0\1\4\1\0"+
    "\1\4\5\0\6\4\1\165\1\4\14\0\11\4\11\0"+
    "\3\4\1\0\1\4\1\0\1\4\5\0\3\4\1\166"+
    "\4\4\14\0\11\4\11\0\3\4\1\0\1\4\1\0"+
    "\1\4\5\0\1\167\7\4\14\0\11\4\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4000];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\11\1\2\11\6\1\3\11"+
    "\6\1\7\11\2\0\1\1\4\0\7\1\7\11\13\1"+
    "\1\0\1\1\1\11\17\1\1\0\34\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	public Token nextToken(String lex, int num){
        return new Token(num, lex);
    }

    public Token nextToken(String lex, int num, int type){
        return new Token(num, lex, type);
    }
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return nextToken("", 0);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Léxico");
            }
          case 50: break;
          case 2: 
            { return nextToken("", 39);
            }
          case 51: break;
          case 3: 
            { return nextToken("", 44);
            }
          case 52: break;
          case 4: 
            { /*ignorar*/
            }
          case 53: break;
          case 5: 
            { return nextToken("", 33);
            }
          case 54: break;
          case 6: 
            { return nextToken("", 20);
            }
          case 55: break;
          case 7: 
            { return nextToken("", 21);
            }
          case 56: break;
          case 8: 
            { return nextToken("", 22);
            }
          case 57: break;
          case 9: 
            { return nextToken("", 32);
            }
          case 58: break;
          case 10: 
            { return nextToken("", 38);
            }
          case 59: break;
          case 11: 
            { return nextToken("", 37);
            }
          case 60: break;
          case 12: 
            { return nextToken("", 28);
            }
          case 61: break;
          case 13: 
            { return nextToken("", 29);
            }
          case 62: break;
          case 14: 
            { return nextToken("", 34);
            }
          case 63: break;
          case 15: 
            { return nextToken("", 35);
            }
          case 64: break;
          case 16: 
            { return nextToken("", 36);
            }
          case 65: break;
          case 17: 
            { return nextToken("", 15);
            }
          case 66: break;
          case 18: 
            { return nextToken("", 16);
            }
          case 67: break;
          case 19: 
            { return nextToken("", 17);
            }
          case 68: break;
          case 20: 
            { return nextToken("", 18);
            }
          case 69: break;
          case 21: 
            { return nextToken("", 19);
            }
          case 70: break;
          case 22: 
            { return nextToken("", 45);
            }
          case 71: break;
          case 23: 
            { return nextToken("", 46);
            }
          case 72: break;
          case 24: 
            { return nextToken("", 40);
            }
          case 73: break;
          case 25: 
            { return nextToken("", 26);
            }
          case 74: break;
          case 26: 
            { return nextToken("", 23);
            }
          case 75: break;
          case 27: 
            { return nextToken("", 24);
            }
          case 76: break;
          case 28: 
            { return nextToken("", 25);
            }
          case 77: break;
          case 29: 
            { return nextToken("", 27);
            }
          case 78: break;
          case 30: 
            { return nextToken("", 30);
            }
          case 79: break;
          case 31: 
            { return nextToken("", 31);
            }
          case 80: break;
          case 32: 
            { return nextToken("", 3);
            }
          case 81: break;
          case 33: 
            { return nextToken("", 8);
            }
          case 82: break;
          case 34: 
            { return nextToken("", 41);
            }
          case 83: break;
          case 35: 
            { return nextToken("", 4);
            }
          case 84: break;
          case 36: 
            { return nextToken("", 42);
            }
          case 85: break;
          case 37: 
            { return nextToken("", 10);
            }
          case 86: break;
          case 38: 
            { return nextToken("", 13);
            }
          case 87: break;
          case 39: 
            { return nextToken("", 2);
            }
          case 88: break;
          case 40: 
            { return nextToken("", 6);
            }
          case 89: break;
          case 41: 
            { return nextToken("", 14);
            }
          case 90: break;
          case 42: 
            { return nextToken("", 43);
            }
          case 91: break;
          case 43: 
            { return nextToken("", 5);
            }
          case 92: break;
          case 44: 
            { return nextToken("", 12);
            }
          case 93: break;
          case 45: 
            { return nextToken("", 9);
            }
          case 94: break;
          case 46: 
            { return nextToken("", 47);
            }
          case 95: break;
          case 47: 
            { return nextToken("", 1);
            }
          case 96: break;
          case 48: 
            { return nextToken("", 7);
            }
          case 97: break;
          case 49: 
            { return nextToken("", 11);
            }
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
